import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeResolutionSignal} from './resolution-signal.mjs';
import {buildIncidentDashboard} from '../../../packages/platform-core/src/incident/dashboard.mjs';
import {OperationsProjector} from '../../../packages/suleia-operations-mcp/src/operations/projector.mjs';
const row=()=>({incidence_id:'201',order_id:'101',raw:{incidentResolution:{incident_id:'201',order_id:'101',observed_at:'2026-10-03T12:00:00Z',customer_replied:true,customer_replied_but_unresolved:true,action_prepared:true,current_owner:'HUMAN',human_review_reason:'CAPABILITY_SHADOW',customer_intents:['WANTS_ORDER'],findings:[{code:'INCIDENT_STUCK',reasons:['ACTION_WITHOUT_VERIFICATION']}],resolution_plan:{plan_id:'a'.repeat(64),steps:[{action:'RETRY_DELIVERY',status:'PREPARED'}]}}}});
test('projection accepts only exact incident/order and strips unstructured customer content',()=>{const r=row();r.raw.incidentResolution.customer_text='private fixture';r.raw.incidentResolution.resolution_plan.address='private fixture';const s=normalizeResolutionSignal(r);assert.ok(s);assert.doesNotMatch(JSON.stringify(s),/private fixture/);r.raw.incidentResolution.order_id='102';assert.equal(normalizeResolutionSignal(r),null);});
test('new filters use persisted observation and retain unobserved records in ordinary view',()=>{const r=row(),base={canonical_issue_id:'fixture',canonical_order_id:'fixture-order',status:'PENDING',is_active:true,created_at:'2026-10-01T12:00:00Z',interpreted_type:'REFUSED_BY_RECIPIENT',chatby_sync_current:true,dropea_sync_current:true};const records=[{...base,resolution_observation:normalizeResolutionSignal(r).observation},{...base,canonical_issue_id:'other'}];for(const resolution of ['replied_unresolved','stuck','prepared'])assert.equal(buildIncidentDashboard(records,{filters:{resolution}}).total,1);assert.equal(buildIncidentDashboard(records).total,2);});
test('projection writes only local exact identity observation and ignores older versions',async()=>{let call;const p=new OperationsProjector({query:async(sql,args)=>{call={sql,args};return {rowCount:1};}});const result=await p.upsertIncidentResolutionObservation(normalizeResolutionSignal(row()));assert.equal(result.actions_executed,0);assert.match(call.sql,/WHERE dropea_issue_id=\$1 AND dropea_order_id=\$2/);assert.match(call.sql,/EXCLUDED.source_updated_at>=/);assert.deepEqual(call.args.slice(0,2),['201','101']);});
