const state={view:'orders',offset:0,limit:50,total:0,filters:{},config:null,token:null,summary:null};
const operationsBase=location.pathname.startsWith('/operations')?'/operations':'';
const $=(id)=>document.getElementById(id);
const text=(value,fallback='—')=>value===undefined||value===null||value===''?fallback:String(value);
const short=(value)=>{const v=text(value);return v.length>22?`${v.slice(0,10)}…${v.slice(-7)}`:v};
const date=(value)=>value?new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const money=(value,currency='EUR')=>value===null||value===undefined?'—':new Intl.NumberFormat('es-ES',{style:'currency',currency:currency||'EUR'}).format(Number(value));
const node=(tag,className,content)=>{const el=document.createElement(tag);if(className)el.className=className;if(content!==undefined)el.textContent=content;return el};

function randomString(){const bytes=crypto.getRandomValues(new Uint8Array(32));return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function redirectUri(){return `${location.origin}${location.pathname}`}

async function beginLogin(){
  const verifier=randomString()+randomString();const loginState=randomString();
  sessionStorage.setItem('suleia_pkce_verifier',verifier);sessionStorage.setItem('suleia_oauth_state',loginState);
  const challenge=await sha256(verifier);const url=new URL(`${state.config.oauth.issuer}/protocol/openid-connect/auth`);
  Object.entries({client_id:state.config.oauth.client_id,response_type:'code',scope:state.config.oauth.scope,redirect_uri:redirectUri(),state:loginState,code_challenge:challenge,code_challenge_method:'S256',audience:state.config.oauth.audience}).forEach(([k,v])=>url.searchParams.set(k,v));
  location.assign(url.toString());
}

async function exchangeCode(code,returnedState){
  const expected=sessionStorage.getItem('suleia_oauth_state');const verifier=sessionStorage.getItem('suleia_pkce_verifier');
  if(!expected||expected!==returnedState||!verifier)throw new Error('La validación de acceso no coincide.');
  const response=await fetch(`${state.config.oauth.issuer}/protocol/openid-connect/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:state.config.oauth.client_id,code,redirect_uri:redirectUri(),code_verifier:verifier})});
  if(!response.ok)throw new Error('No se pudo completar el acceso seguro.');const payload=await response.json();
  sessionStorage.removeItem('suleia_pkce_verifier');sessionStorage.removeItem('suleia_oauth_state');
  sessionStorage.setItem('suleia_access_token',payload.access_token);sessionStorage.setItem('suleia_token_expires_at',String(Date.now()+payload.expires_in*1000));
  history.replaceState({},document.title,location.pathname);return payload.access_token;
}

function activeToken(){const token=sessionStorage.getItem('suleia_access_token');const expires=Number(sessionStorage.getItem('suleia_token_expires_at')||0);return token&&expires>Date.now()+15000?token:null}
async function api(path){const response=await fetch(`${operationsBase}${path}`,{headers:{Authorization:`Bearer ${state.token}`}});if(response.status===401||response.status===403){signOut(false);throw new Error('Tu sesión ha caducado.');}if(!response.ok)throw new Error('La lectura no está disponible temporalmente.');return (await response.json()).data}
function signOut(remote=true){sessionStorage.removeItem('suleia_access_token');sessionStorage.removeItem('suleia_token_expires_at');state.token=null;$('app').hidden=true;$('login').hidden=false;if(remote&&state.config){const url=new URL(`${state.config.oauth.issuer}/protocol/openid-connect/logout`);url.searchParams.set('client_id',state.config.oauth.client_id);url.searchParams.set('post_logout_redirect_uri',redirectUri());location.assign(url.toString());}}

function badge(value){const v=text(value);const lower=v.toLowerCase();let tone='gray';if(/ready|pass|exact|verified|delivered|finish|resolved/.test(lower))tone='green';else if(/wait|pending|medium|review|active/.test(lower))tone='amber';else if(/high|critical|blocked|error|stale|conflict|reject|return/.test(lower))tone='red';else if(/human/.test(lower))tone='purple';else if(/info|shipping|transit/.test(lower))tone='blue';return node('span',`badge ${tone}`,v)}
function summaryCard(label,value,detail){const card=node('article','summary-card');card.append(node('span','',label),node('strong','',text(value,'0')),node('small','',detail));return card}

function renderSummary(){const root=$('summary');root.replaceChildren();const data=state.view==='orders'?state.summary?.orders:state.summary?.incidents;const protections=state.summary?.protections||{};if(state.view==='orders')root.append(summaryCard('Pedidos observados',data?.total,'Copia operativa'),summaryCard('Duplicados',protections.duplicate_orders,'Bloqueo preventivo'),summaryCard('Pedidos TEST',protections.test_orders,'Nunca automáticos'),summaryCard('Chatby elegibles',protections.chatby_delete_eligible,'Solo previsualización'),summaryCard('Releasit pendientes',protections.releasit_pending,'Escritura desactivada'),summaryCard('Revisión humana',protections.human_review,'Protecciones'));else root.append(summaryCard('Pendientes',data?.pending,'Activas y accionables'),summaryCard('Esperando cliente',data?.awaiting_customer,'Timer en curso'),summaryCard('Riesgo alto',data?.high_risk,'Revisión prioritaria'),summaryCard('Bloqueadas',data?.blocked,'Sin acción posible'));const last=state.view==='orders'?(protections.last_reconciled_at||data?.last_sync_at):data?.last_sync_at;$('last-sync').textContent=date(last);if(data?.stale>0)showNotice('Hay datos desactualizados. Las decisiones afectadas permanecen bloqueadas.');}
function showNotice(message){const el=$('notice');el.textContent=message;el.hidden=!message}

const filterDefinitions={orders:[['status','Estado',['PENDING','CONFIRMED','PROCESSING','SHIPPING','FINISH','ERROR']],['decision','Decisión',['NOT_ASSESSED','WAITING','READY','HUMAN_REVIEW','BLOCKED']],['protection','Protección',['DUPLICATE_ACTIVE_ORDER','TEST_ORDER','CHATBY_DELETE_ELIGIBLE','CHATBY_DELETE_FAILED','RELEASIT_PENDING','RELEASIT_BLOCKED','RELEASIT_ERROR','PROTECTION_REVIEW']],['freshness','Datos',['FRESH','STALE','UNKNOWN']]],incidents:[['type','Tipo',['RECIPIENT_ABSENT','ADDRESS_INCORRECT','PENDING_DATA','REFUSED_BY_RECIPIENT','POSSIBLE_RETURN','RETURN_REQUESTED','PICKUP_AT_AGENCY','DELIVERY_FAILED','ADMINISTRATIVE_ISSUE','PENDING_AUTHORIZATION','RETAINED','CUSTOMS_ISSUE','DAMAGED_PACKAGE','LOST_PACKAGE','GENERAL_INCIDENCE','UNKNOWN']],['response','Respuesta',['RESPONDED','NO_RESPONSE','UNKNOWN']],['resolution','Propuesta',['RETRY','CHANGE_ADDRESS','PICKUP_AT_AGENCY','RETURN_REQUESTED','SOLUTION_PROVIDED']],['risk','Riesgo',['LOW','MEDIUM','HIGH','CRITICAL']],['freshness','Datos',['FRESH','STALE','UNKNOWN']]]};
function renderFilters(){const root=$('filters');root.replaceChildren();for(const [key,label,options] of filterDefinitions[state.view]){const select=node('select','filter-select');select.setAttribute('aria-label',label);select.append(new Option(`Todos · ${label}`,'')).value=state.filters[key]||'';for(const option of options)select.append(new Option(option,option));select.addEventListener('change',()=>{state.filters[key]=select.value;state.offset=0;loadQueue()});root.append(select)}}
function cell(content,className=''){const td=node('td',className);td.append(content instanceof Node?content:document.createTextNode(text(content)));return td}
function protectionBadges(item){const box=node('div','protection-badges');if(item.duplicate_status==='DUPLICATE_ACTIVE_ORDER')box.append(badge('DUPLICADO'));if(item.test_order)box.append(badge('TEST'));if(item.chatby_cleanup_status==='DELETE_ELIGIBLE')box.append(badge('CHATBY CLEANUP'));if(['BLOCK_ELIGIBLE','BLOCK_PENDING','BLOCK_REQUESTED','BLOCKED_VERIFIED'].includes(item.return_block_status))box.append(badge('RETURN BLOCK'));if(item.protection_review)box.append(badge('REVIEW'));if(!box.childNodes.length)box.append(node('span','muted','—'));return box}
function rowOrder(item){const tr=node('tr');tr.tabIndex=0;tr.append(cell(short(item.dropea_order_id),'mono'),cell(badge(item.canonical_state)),cell(item.product_summary?.total_units??'—'),cell(money(item.total_amount,item.currency)),cell(badge(item.identity_status)),cell(protectionBadges(item)),cell(badge(item.decision_status)),cell(badge(item.freshness)),cell(date(item.updated_at)));tr.addEventListener('click',()=>openDetail(item.canonical_order_id));tr.addEventListener('keydown',e=>{if(e.key==='Enter')openDetail(item.canonical_order_id)});return tr}
function rowIncident(item){const tr=node('tr');tr.tabIndex=0;tr.append(cell(short(item.dropea_issue_id),'mono'),cell(badge(item.type)),cell(badge(item.customer_response_status)),cell(badge(item.proposed_resolution||'SIN PROPUESTA')),cell(badge(item.risk)),cell(badge(item.qa_result)),cell(date(item.due_at)),cell(badge(item.freshness)),cell(date(item.updated_at)));tr.addEventListener('click',()=>openDetail(item.canonical_issue_id));tr.addEventListener('keydown',e=>{if(e.key==='Enter')openDetail(item.canonical_issue_id)});return tr}
function renderHead(){const labels=state.view==='orders'?['Pedido','Estado','Unidades','Importe','Identidad','Protecciones','Decisión','Datos','Actualizado']:['Incidencia','Tipo','Cliente','Propuesta','Riesgo','QA','Vence','Datos','Actualizado'];const tr=node('tr');labels.forEach(label=>tr.append(node('th','',label)));$('table-head').replaceChildren(tr)}

async function loadQueue(){showNotice('');const params=new URLSearchParams({limit:String(state.limit),offset:String(state.offset)});Object.entries(state.filters).forEach(([k,v])=>{if(v)params.set(k,v)});try{const data=await api(`/api/operations/${state.view}?${params}`);state.total=data.total;const body=$('table-body');body.replaceChildren(...data.items.map(state.view==='orders'?rowOrder:rowIncident));$('empty-state').hidden=data.items.length>0;$('result-count').textContent=`${data.total} registros`;$('prev-page').disabled=state.offset===0;$('next-page').disabled=state.offset+state.limit>=data.total;}catch(error){showNotice(error.message)}}
function field(label,value,asBadge=false){const el=node('div','field');el.append(node('span','',label),asBadge?badge(value):node('strong','',text(value)));return el}
function section(title,fields,className=''){const box=node('section',`detail-section ${className}`.trim());box.append(node('h3','',title));const grid=node('div','field-grid');fields.forEach(item=>grid.append(field(...item)));box.append(grid);return box}
function timeline(items){const box=node('section','detail-section');box.append(node('h3','', 'Cronología'));const list=node('div','timeline');for(const item of items||[]){const row=node('div','timeline-item');row.append(node('strong','',text(item.event_type)),node('span','',`${date(item.occurred_at)} · ${text(item.source)} · ${text(item.freshness)}`));list.append(row)}if(!(items||[]).length)list.append(node('span','', 'Sin eventos disponibles'));box.append(list);return box}
function incidentDiscountSection(i){if(i.type!=='REFUSED_BY_RECIPIENT')return document.createDocumentFragment();return section('Descuento',[['Estado',i.discount_status,true],['Importe original',money(i.original_amount)],['Descuento',money(i.discount_amount)],['Nuevo importe',money(i.new_amount)],['Email preparado',i.email_prepared?'SÍ':'NO'],['Email enviado','NO'],['Cambio COD',i.cod_change_verified?'VERIFICADO':'PENDIENTE'],['Listo para retry',i.ready_for_retry?'SÍ':'NO']])}
async function openDetail(id){
  $('drawer-backdrop').hidden=false;$('detail-drawer').classList.add('open');$('detail-drawer').setAttribute('aria-hidden','false');
  $('detail-title').textContent='Cargando…';$('detail-content').replaceChildren();
  try{
    const data=await api(`/api/operations/${state.view}/${encodeURIComponent(id)}`);const root=$('detail-content');
    if(state.view==='orders'){
      const o=data.order;$('detail-title').textContent=`Pedido ${short(o.dropea_order_id)}`;
      root.append(
        section('Pedido',[['Estado',o.canonical_state,true],['Ciclo de vida',o.lifecycle_classification,true],['Status',o.status],['Importe',money(o.total_amount,o.currency)],['Identidad',o.identity_status,true],['Teléfono',o.phone_last4?`***${o.phone_last4}`:'—'],['Datos',o.freshness,true]]),
        section('PROTECCIONES OPERATIVAS',[['Producto canónico',short(o.canonical_product_key)],['Duplicado',o.duplicate_status,true],['Pedido en conflicto',short(o.conflicting_order_id)],['Confirmación automática',o.automatic_confirmation_allowed?'PERMITIDA':'BLOQUEADA',true],['Pedido TEST',o.test_order?'SÍ':'NO',true],['Estado Chatby',o.chatby_cleanup_status,true],['Blockers Chatby',(o.chatby_cleanup_blockers||[]).join(', ')||'NINGUNO'],['Elegibilidad Releasit',o.return_block_status,true],['Motivo',o.return_block_reason||'—'],['Revisión',o.protection_review?'REQUERIDA':'NO',true],['Última reconciliación',date(o.protection_last_reconciled_at)]]),
        section('Conversación',[['Estado',o.conversation_status||'UNKNOWN',true],['Motivo',o.conversation_reason||'—'],['Frescura',o.conversation_freshness||'UNKNOWN',true],['Respondió',o.customer_replied||o.has_customer_replied?'SÍ':'NO'],['Último cliente',date(o.last_customer_message_at||o.latest_inbound_message_at)],['Último Suleia',date(o.last_suleia_message_at)],['Último botón',o.last_button||'—',true],['Última plantilla',short(o.latest_template_hash)],['Intención',o.detected_intent,true],['Confidence',o.conversation_confidence],['Contradicción',o.contradiction,true]]),
        timeline(data.timeline));
    }else{
      const i=data.incident;$('detail-title').textContent=`Incidencia ${short(i.dropea_issue_id)}`;
      root.append(
        section('Situación logística',[['Tipo',i.type,true],['Estado',i.status,true],['Activa',i.is_active?'SÍ':'NO'],['Transportista',i.carrier],['Tracking',short(i.tracking_reference_masked)],['Código carrier',i.initial_carrier_code],['Intento',i.delivery_attempt_number],['Vence',date(i.due_at)]]),
        section('Conversación',[['Estado',i.conversation_status||'UNKNOWN',true],['Motivo',i.conversation_reason||'—'],['Identidad',i.conversation_identity_method||'—'],['Frescura',i.conversation_freshness||'UNKNOWN',true],['Respondió',i.customer_replied||i.has_customer_replied?'SÍ':'NO'],['Último cliente',date(i.last_customer_message_at||i.latest_inbound_message_at)],['Último Suleia',date(i.last_suleia_message_at)],['Último botón',i.last_button||'—',true],['Última plantilla',short(i.latest_template_hash)],['Intención',i.detected_intent,true],['Confidence',i.conversation_confidence],['Fecha solicitada',i.requested_date],['Franja',i.requested_time_window],['Contradicción',i.contradiction,true]]),
        section('Decision Card',[['Propuesta',i.proposed_resolution||'REVISIÓN HUMANA',true],['Política',i.decision_policy_version],['Validación Dropea',i.dropea_validation,true],['Viabilidad GLS',i.gls_feasibility,true],['Riesgo',i.risk,true],['QA',i.qa_result,true],['Acciones ejecutadas','0']],'decision-card'),incidentDiscountSection(i),timeline(data.timeline));
    }
  }catch(error){$('detail-content').append(node('div','notice',error.message))}
}
function closeDetail(){$('drawer-backdrop').hidden=true;$('detail-drawer').classList.remove('open');$('detail-drawer').setAttribute('aria-hidden','true')}
async function refresh(){try{state.summary=await api('/api/operations/summary');renderSummary();await loadQueue()}catch(error){showNotice(error.message)}}
function setView(view){state.view=view;state.offset=0;state.filters={};document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view));$('view-title').textContent=view==='orders'?'Pedidos':'Incidencias';$('queue-title').textContent=view==='orders'?'Pedidos observados':'Incidencias pendientes';renderHead();renderFilters();renderSummary();loadQueue()}

async function init(){
  state.config=await fetch(`${operationsBase}/api/config`).then(r=>{if(!r.ok)throw new Error('Configuración privada no disponible.');return r.json()});
  const params=new URLSearchParams(location.search);state.token=activeToken();if(params.has('code'))state.token=await exchangeCode(params.get('code'),params.get('state'));
  if(!state.token){$('login').hidden=false;$('app').hidden=true;return}
  $('login').hidden=true;$('app').hidden=false;renderHead();renderFilters();await refresh();setInterval(()=>{if(document.visibilityState==='visible'&&activeToken())refresh()},state.config.refresh_interval_seconds*1000);
}
$('login-button').addEventListener('click',beginLogin);$('logout-button').addEventListener('click',()=>signOut(true));$('refresh-button').addEventListener('click',refresh);$('prev-page').addEventListener('click',()=>{state.offset=Math.max(0,state.offset-state.limit);loadQueue()});$('next-page').addEventListener('click',()=>{state.offset+=state.limit;loadQueue()});document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>setView(item.dataset.view)));$('close-drawer').addEventListener('click',closeDetail);$('drawer-backdrop').addEventListener('click',closeDetail);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDetail()});
init().catch(error=>{$('login').hidden=false;$('app').hidden=true;const card=document.querySelector('.login-card');card.append(node('div','notice',error.message))});
