/* Read-only renderer: all decisions, rates and status labels come from the API. */
const AutomationPanel=(()=>{
 let filters={period:'7d'},request=0;
 const pill=(label,tone='gray')=>node('span',`ip-badge ${tone}`,label??'Sin evidencia');
 const modeBadge=s=>pill(s.label_mode,{LIVE:'green',CANARY:'amber',SHADOW:'violet',OFF:'gray'}[s.mode]||'gray');
 function pipeline(stages){const root=node('div','automation-pipeline');for(const s of stages){const step=node('div','automation-stage');step.append(node('small','',s.label),modeBadge(s));root.append(step);}return root;}
 function group(title,...children){const g=node('section','automation-card');g.append(node('h3','',title),...children);return g;}
 function actionRow(a){const row=node('div','automation-recent-row');row.append(node('span','automation-time',date(a.occurred_at)),node('strong','',a.label),pill(a.status_label,a.execution_status==='VERIFIED'?'green':a.execution_status==='UNKNOWN'?'rose':'amber'),node('small','',a.evidence_mode==='SHADOW'?'Simulación · sin acción externa':a.provider));return row;}
 function detail(data){const w=data.workflow;closeDetail();$('detail-title').textContent=`Automatización · ${w.label}`;
  const root=$('detail-content');root.replaceChildren();
  root.append(group('Resumen',node('p','',w.current_activity),pipeline(w.stages)),group('Playbook',node('p','automation-playbook',w.playbook.join(' → '))),
   section('Controles · solo lectura',[['Interruptor principal',w.master==='ACTIVE'?'Activo':w.master==='DISABLED'?'Deshabilitado':'Sin evidencia'],...Object.entries(w.controls).map(([key,value])=>[({automation_live:'Automatización',notification_enabled:'Avisos',interpretation_enabled:'Interpretación real',resolution_enabled:'Resolución',pickup_enabled:'Agencia',return_enabled:'Devoluciones'})[key],value===null?'Sin evidencia':value?'Habilitado':'Deshabilitado'])]),
   section('Canary',[['Estado',w.canary.active?'Activo':'Sin canary activo'],['Límite',w.canary.limit??'No aplica'],['Usados',w.canary.used??'No aplica'],['Disponibles',w.canary.remaining??'No aplica'],['Candidato',w.canary.candidate?'Seleccionado; ver referencia en Debug':'Sin candidato'],['Resultado',w.canary.result]]),
   section('Protecciones',w.breakers.map(b=>[b.label,`${b.label_status}${b.opened_at?' · '+date(b.opened_at):''}`])),
   section('Observabilidad',[['Salud',w.health==='HEALTHY'?'Saludable':w.health==='UNHEALTHY'?'Necesita atención':'Sin evidencia'],['Último ciclo',date(w.observer?.last_completed_at)],['Retraso',w.observer?.lag_seconds==null?'Sin evidencia':`${Math.round(w.observer.lag_seconds)} s`],['Reservas',w.counts.reservations],['Avisos verificados',w.counts.notifications],['Temporizadores',w.counts.timers],['Callbacks',w.counts.callbacks??'Sin evidencia'],['Resoluciones verificadas',w.counts.resolutions]]),
   group('Métricas',...data.metrics.map(m=>node('p','',`${m.label}: ${m.value==null?'Sin evidencia':m.value+' %'} · ${m.definition}`))),
   group('Errores',...(data.alerts.length?data.alerts.map(a=>node('p','',a.reason)):[node('p','','Sin errores acreditados en las fuentes disponibles.')])),
   group('Acciones recientes',...(data.actions.length?data.actions.map(actionRow):[node('p','','No hay acciones automáticas verificadas en este periodo.')])),
   section('Configuración',[['Fuente',w.source],['Corte de plantilla',date(w.cutover)],['Cambios desde este panel','No permitidos']]));
  const debug=node('details','automation-debug');debug.append(node('summary','','Debug'),node('pre','',JSON.stringify({workflow:w.id,canary_candidate:w.canary.candidate,breakers:w.breakers,stages:w.stages},null,2)));root.append(debug);
  $('detail-drawer').classList.add('open');$('detail-drawer').setAttribute('aria-hidden','false');$('drawer-backdrop').hidden=false;
 }
 async function open(id){const generation=++state.detailRequest;try{const data=await api(`/api/operations/automation/workflows/${encodeURIComponent(id)}?period=${encodeURIComponent(filters.period)}`);if(generation===state.detailRequest&&state.view==='automation')detail(data);}catch(e){showNotice(e.message);}}
 function render(data){const root=$('automation-view');root.replaceChildren(node('p','automation-subtitle','Control, autonomía y salud de los workflows operativos.'));
  const cards=node('div','summary-grid automation-summary');
  for(const [key,label,value,tone] of [['active','Workflows activos',data.summary.active,'green'],['live','En LIVE',data.summary.live,'green'],['canary','En CANARY',data.summary.canary,'amber'],['shadow','En SHADOW',data.summary.shadow,'purple'],['breakers','Protecciones abiertas',data.summary.breakers,'red'],['human_today','Intervenciones hoy',data.summary.human_today,'']])cards.append(summaryCard(label,value??'—',value==null?'Cobertura no disponible':'Ver workflows relacionados',tone,()=>{if(key==='human_today'){showNotice('La cobertura de intervenciones humanas no está disponible; una revisión pendiente no cuenta como intervención realizada.');return;}filters={period:filters.period,...(key==='active'?{active:'true'}:key==='breakers'?{breaker:'OPEN'}:['live','canary','shadow'].includes(key)?{mode:key.toUpperCase()}:{} )};load();}));root.append(cards);
  const toolbar=node('div','automation-card automation-filters');
  const definitions=[['workflow','Workflow',data.available_workflows.map(w=>[w.id,w.label])],['stage','Etapa',[['detection','Detectar'],['notification','Contactar'],['interpretation','Interpretar'],['decision','Decidir'],['resolution','Ejecutar'],['verification','Verificar']]],['mode','Modo',['OFF','SHADOW','CANARY','LIVE'].map(v=>[v,v])],['breaker','Protección',[['OPEN','Abierta'],['CLOSED','Cerrada']]],['health','Salud',[['HEALTHY','Saludable'],['UNHEALTHY','Necesita atención'],['UNKNOWN','Sin evidencia']]],['period','Periodo',[['today','Hoy'],['7d','Últimos 7 días'],['30d','Últimos 30 días']]]];
  for(const [key,label,options]of definitions){const box=node('label','incident-filter-field',label),select=node('select','filter-select');select.setAttribute('aria-label',label);if(key!=='period')select.append(new Option('Todos',''));for(const [value,title]of options)select.append(new Option(title,value));select.value=filters[key]||'';select.addEventListener('change',()=>{filters[key]=select.value;load();});box.append(select);toolbar.append(box);}root.append(toolbar);
  const autonomy=group('Autonomía operativa',node('p','',data.definitions.period)),metrics=node('div','automation-metrics');
  for(const m of data.metrics){const card=node('article','automation-metric');card.append(node('span','',m.label),node('strong','',m.value==null?'—':`${m.value} %`),node('small','',m.value==null?'Sin evidencia suficiente':`${m.numerator} / ${m.denominator} incidencias`));card.title=m.definition;const explanation=node('details');explanation.append(node('summary','','Definición'),node('small','',m.definition));card.append(explanation);metrics.append(card);}autonomy.append(metrics);root.append(autonomy);
  const table=node('table','automation-table'),head=node('thead'),hr=node('tr');for(const title of ['Workflow','Contacto','Interpretación','Decisión','Ejecución','Verificación','Estado / protección','Última actividad'])hr.append(node('th','',title));head.append(hr);const body=node('tbody');
  for(const w of data.workflows){const tr=node('tr','ip-row');tr.tabIndex=0;tr.setAttribute('aria-label',`Abrir workflow ${w.label}`);const identity=node('div','ip-copy');identity.append(node('strong','',w.label),node('small','',w.current_activity));tr.append(cell(identity));for(const id of ['notification','interpretation','decision','resolution','verification'])tr.append(cell(modeBadge(w.stages.find(s=>s.id===id))));const status=node('div','ip-copy');status.append(pill(w.master==='ACTIVE'?'Activo':w.master==='DISABLED'?'Deshabilitado':'Sin evidencia',w.master==='ACTIVE'?'green':'gray'),node('small','',w.breakers.some(b=>b.status==='OPEN')?'Protección abierta':'Sin protección abierta acreditada'));tr.append(cell(status),cell(date(w.last_activity)));tr.addEventListener('click',()=>open(w.id));tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(w.id);}});body.append(tr);}table.append(head,body);const wrap=node('div','table-wrap');wrap.append(table);root.append(group('Workflows operativos',wrap,...(!data.workflows.length?[node('p','','No hay workflows para estos filtros.')]:[])));
  const bottom=node('div','automation-bottom');bottom.append(group('Acciones recientes',...(data.actions.length?data.actions.slice(0,12).map(actionRow):[node('p','','No hay acciones registradas en el periodo.')])),group('Necesita atención',...(data.alerts.length?data.alerts.map(a=>node('p','',`${a.label} · ${a.reason}`)):[node('p','','Sin alertas acreditadas. Los datos desconocidos siguen indicados como «Sin evidencia».')])));root.append(bottom,node('p','automation-footnote',data.definitions.coverage));$('last-sync').textContent=date(data.checked_at);
 }
 async function load(){const id=++request;try{const data=await api('/api/operations/automation/overview?'+new URLSearchParams(filters));if(id!==request||state.view!=='automation')return;render(data);showNotice('');}catch(e){if(id===request)showNotice(e.message);}}
 function incidentDetail(i){const root=node('div','automation-incident-detail');if(!i.next_best_action)return root;root.append(section('Decisión de Suleia',[['Qué ocurrió',translated(i.interpreted_type)],['Qué dijo el cliente',i.recovery?.evidence?.message||'Sin mensaje verificable'],['Qué entendió Suleia',i.next_best_action.reason],['Qué decidió',i.next_best_action.label],['Por qué',i.next_best_action.blocking_reasons.join(' · ')||i.next_best_action.reason],['Autonomía',i.autonomy.label]]),section('Confianza',[['Evidencia',i.confidence.evidence],['Intención',i.confidence.intent],['Ejecución',i.confidence.execution]]),section('Ejecución y verificación',[['Acción',i.execution.action_label],['Estado',i.execution.label],['Proveedor',i.execution.provider||'Sin ejecución registrada'],['Solicitada',date(i.execution.requested_at)],['Ejecutada',date(i.execution.executed_at)],['Verificada',date(i.execution.verified_at)],['Bloqueos',i.execution.blocking_reasons.join(' · ')||'Ninguno registrado']]));return root;}
 return {load,render,detail,pipeline,incidentDetail};
})();
