import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {workflowPresentation} from '../../packages/platform-core/src/incident/automation-presentation.mjs';
class E{constructor(tag,cls='',text=''){this.tagName=tag;this.className=cls;this.textContent=text;this.children=[];this.events={};this.classList={add(){},remove(){}};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.events[k]=v;}}
const all=e=>[e,...e.children.flatMap(x=>typeof x==='object'?all(x):[])],text=e=>[e.textContent,...e.children.map(x=>typeof x==='object'?text(x):x)].join(' ');
const fixture=()=>({summary:{active:1,live:1,canary:1,shadow:1,breakers:0,human_today:null},available_workflows:[{id:'RECIPIENT_ABSENT',label:'Ausente'}],workflows:[workflowPresentation({workflow:'RECIPIENT_ABSENT',notification_mode:'CANARY',resolution_mode:'DISABLED',automation_live:true,canary_issue_id:'example',reservations:0})],metrics:[{label:'Resolución autónoma',value:null,definition:'Sin cobertura'}],actions:[],alerts:[],definitions:{period:'Periodo real',coverage:'Cobertura real'},checked_at:'2026-09-26T10:00:00Z'});
function setup(){const els=new Map(),get=id=>{if(!els.has(id))els.set(id,new E('div'));return els.get(id);};const c={URLSearchParams,state:{view:'automation'},$:get,node:(...x)=>new E(...x),date:v=>v||'Sin evidencia',cell:v=>{const e=new E('td');e.append(v);return e;},section:(title,rows)=>new E('section','',title+' '+JSON.stringify(rows)),closeDetail(){},showNotice(){},Option:class extends E{constructor(label,value){super('option','',label);this.value=value;}},summaryCard:(label,value,detail,tone,click)=>{const e=new E('button',tone,label+' '+value+' '+detail);e.events.click=click;return e;},api:async path=>{c.lastPath=path;return fixture();}};vm.runInNewContext(fs.readFileSync(new URL('./automation-panel.js',import.meta.url),'utf8')+'\nglobalThis.ui=AutomationPanel;',c);return {c,get};}
test('six clickable cards, workflow stages and true empty states',()=>{const{c,get}=setup();c.ui.render(fixture());const s=text(get('automation-view'));assert.match(s,/CANARY/);assert.match(s,/OFF/);assert.match(s,/No hay acciones registradas/);assert.match(s,/Sin evidencia suficiente/);assert.equal(all(get('automation-view')).filter(e=>e.tagName==='button').length,6);});
test('workflow filters issue one aggregate read and keep period',async()=>{const{c,get}=setup();c.ui.render(fixture());const f=all(get('automation-view')).find(e=>e.tagName==='select'&&e['aria-label']==='Modo');f.value='CANARY';await f.events.change();await Promise.resolve();assert.match(c.lastPath,/mode=CANARY/);assert.match(c.lastPath,/period=7d/);});
test('workflow drawer exposes controls, canary, playbook, metrics, errors and debug without switches',()=>{const{c,get}=setup(),data=fixture();c.ui.detail({...data,workflow:data.workflows[0]});const s=text(get('detail-content'));for(const label of ['Controles','Canary','Playbook','Métricas','Errores','Debug'])assert.ok(s.includes(label));assert.match(s,/No hay canary ejecutado/);assert.equal(get('detail-drawer')['aria-hidden'],'false');assert.equal(all(get('detail-content')).some(e=>['input','select'].includes(e.tagName)),false);});
test('provider text is inert DOM text, not HTML',()=>{const{c,get}=setup(),data=fixture();data.alerts=[{label:'Ausente',reason:'<img src=x onerror=1>'}];c.ui.render(data);assert.match(text(get('automation-view')),/<img/);assert.equal(all(get('automation-view')).some(e=>e.tagName==='img'),false);});
test('responsive table scroll is local and layouts shrink at tablet widths',()=>{const css=fs.readFileSync(new URL('./automation-panel.css',import.meta.url),'utf8');for(const width of [1400,900,600])assert.ok(css.includes(`max-width:${width}px`));assert.match(css,/minmax\(0,1fr\)/);assert.match(css,/min-width:960px/);const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.match(html,/data-view="automation"/);});
