import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {buildIncidentDashboard} from '../../packages/platform-core/src/incident/dashboard.mjs';
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.events={};this.style={};this.classList={add(){},remove(){},toggle(){}};}append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;}setAttribute(k,v){this[k]=String(v);}addEventListener(k,v){this.events[k]=v;}}
const text=e=>typeof e==='string'?e:[e.textContent,...e.children.map(text)].join(' '),all=e=>[e,...e.children.flatMap(c=>typeof c==='string'?[]:all(c))];
function setup(){const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};const context={URL,URLSearchParams,Intl,console,Node:Element,AbortController,setInterval(){},location:{origin:'https://example.invalid',pathname:'/operations/',search:''},history:{replaceState(){}},sessionStorage:{getItem(){return null;},setItem(){},removeItem(){}},Option:class extends Element{constructor(label,value){super('option');this.textContent=label;this.value=value;}},document:{getElementById:get,createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),createTextNode:String,querySelectorAll:()=>[],addEventListener(){}},fetch:async()=>({ok:true,json:async()=>({oauth:{}})})};
vm.runInNewContext(fs.readFileSync(new URL('./incident-panel.js',import.meta.url),'utf8')+'\n'+fs.readFileSync(new URL('./app.js',import.meta.url),'utf8')+'\nloadQueue=async()=>{globalThis.loads=(globalThis.loads||0)+1};openDetail=id=>{globalThis.opened=id};globalThis.ui={state,rowIncident,renderFilters,renderHead,renderSummary};',context);
const records=[{canonical_issue_id:'fixture',canonical_order_id:'order',dropea_issue_id:'example',external_order_reference:'#123',created_at:'2026-09-20T10:00:00Z',status:'PENDING',is_active:true,interpreted_type:'REFUSED_BY_RECIPIENT',customer_name:'Persona Ejemplo -',chatby_sync_current:false,dropea_sync_current:true}];
const data=buildIncidentDashboard(records,{now:'2026-09-21T10:00:00Z'});context.ui.state.view='incidents';context.ui.state.filters={scope:'ACTIVE'};context.ui.state.summary={incidents:data.summary};return {context,get,data};}
test('reference renderer uses eight compact semantic cells, safe evidence and keyboard drawer',()=>{const {context,data}=setup(),row=context.ui.rowIncident(data.items[0]);assert.equal(row.children.length,8);assert.ok(all(row).some(e=>e.className==='ip-avatar'&&e.textContent==='PE'));assert.doesNotMatch(text(row),/Persona Ejemplo -|UNKNOWN_|SHADOW_READ_ONLY|INCIDENCE/);assert.match(text(row),/Rechazo|Plazo no verificable|Acción bloqueada/);assert.equal(all(row).some(e=>e.className==='signal-cell'),false);row.events.keydown({key:'Enter',preventDefault(){}});assert.equal(context.opened,'fixture');});
test('two main tabs retain follow-up as a separate current filter; search and chips apply shared state',()=>{const {context,get}=setup();context.ui.renderFilters();const root=get('filters'),tabs=all(root).find(e=>e.className==='incident-scope-tabs');assert.equal(tabs.children.length,2);const scope=all(root).find(e=>e.tagName==='select'&&e['aria-label']==='Alcance');assert.match(text(scope),/Seguimiento/);assert.doesNotMatch(text(scope),/Histórico/);const search=all(get('incident-search-bar')).find(e=>e.tagName==='input');search.value='persona';search.events.keydown({key:'Enter'});assert.equal(context.ui.state.filters.q,'persona');const chip=all(root).find(e=>e.className?.includes('ip-chip')&&e.textContent.startsWith('Rechazo'));chip.events.click();assert.equal(context.ui.state.filters.type,'REFUSED_BY_RECIPIENT');assert.equal(context.ui.state.offset,0);tabs.children[1].events.click();context.ui.renderFilters();assert.equal(context.ui.state.filters.scope,'HISTORICAL');assert.match(text(get('filters')),/Desde/);});
test('sorting exposes direction and resets pagination; six cards retain canonical counts',()=>{const {context,get,data}=setup();context.ui.renderHead();context.ui.state.offset=10;const button=all(get('table-head')).find(e=>e.tagName==='button'&&e.textContent.startsWith('Cliente'));button.events.click();assert.equal(context.ui.state.filters.sort,'customer');assert.equal(context.ui.state.offset,0);assert.match(text(get('table-head')),/Prioridad/);context.ui.renderSummary();assert.equal(get('summary').children.length,6);for(const k of data.summary.dashboard.kpis)assert.ok(text(get('summary')).includes(k.label));});
test('untrusted message remains text and cannot create an image element',()=>{const {context,data}=setup(),item=data.items[0];item.recovery.evidence.message='<img src=x onerror=alert(1)>';const row=context.ui.rowIncident(item);assert.ok(text(row).includes('<img'));assert.equal(all(row).some(e=>e.tagName==='img'),false);});
test('responsive styles isolate colors and contain horizontal overflow locally',()=>{const css=fs.readFileSync(new URL('./incident-panel.css',import.meta.url),'utf8');assert.match(css,/min-width:1060px/);assert.match(css,/height:84px/);assert.match(css,/max-width:1400px/);assert.doesNotMatch(css,/(?:^|[,}])\.(?:green|blue|rose|gray)\{/m);const base=fs.readFileSync(new URL('./styles.css',import.meta.url),'utf8');assert.match(base,/\.table-wrap\{overflow-x:auto;max-width:100%/);});
