import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('Operations Center exposes Pedidos, Incidencias and truthful Control de gasto with no write controls', () => {
  const html = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  const loginCss = fs.readFileSync(new URL('./login.css', import.meta.url), 'utf8');
  assert.equal((html.match(/class="nav-item/g) || []).length, 3);
  assert.match(html, />Pedidos</);
  assert.match(html, />Incidencias</);
  assert.match(html, />Control de gasto</);
  assert.doesNotMatch(`${html}\n${script}\n${css}`, /shopify/i);
  assert.equal((script.match(/method\s*:\s*['"]POST['"]/gi) || []).length, 2);
  assert.match(script, /openid-connect\/token/);
  assert.doesNotMatch(script, /method\s*:\s*['"](?:PUT|PATCH|DELETE)['"]/i);
  assert.match(html, /Acciones ejecutadas: 0/);
  assert.match(html, /MODO SOLO LECTURA/);
  assert.match(html, /LA LÓGICA PRODUCTIVA NO SE MODIFICA/);
  assert.match(html, /ACCIONES EJECUTADAS: 0/);
  assert.match(html, /id="finance-view"/);
  assert.match(html, /fuente conciliada/);
  assert.match(script, /data\.costs/);
  assert.doesNotMatch(script, /costs\?\.total\s*\|\|\s*0/);
  assert.match(script, /lifecycle_status/);
  assert.match(script, /simulated_decision/);
  assert.match(script, /customer_response_status/);
  assert.match(script, /normalized_type/);
  assert.match(script, /customer_evidence/);
  assert.match(script, /customer_signal_confidence/);
  assert.match(script, /incidents\/overview/);
  assert.match(script, /queueController\?\.abort/);
  assert.match(script, /detailController\?\.abort/);
  assert.match(script, /state\.offset >= data\.total/);
  assert.match(script, /tailored_recommendation/);
  assert.match(script, /source_truth/);
  assert.match(script, /Solución propuesta para esta incidencia/);
  assert.match(script, /Tu feedback se guarda como memoria operativa/);
  assert.match(script, /Acciones externas', '0'/);
  assert.doesNotMatch(script, /\b(?:canonical_state|proposed_resolution)\b/);
  assert.match(html, /<a id="login-button" class="primary-button" href="#" aria-disabled="true"/);
  assert.match(html, /id="login-notice"[^>]*role="alert"/);
  assert.match(html, /<link rel="stylesheet" href="login\.css\?v=20260808-hidden-fix-a00fe6d">/);
  assert.match(html, /<link rel="stylesheet" href="styles\.css\?v=20260819-operations-audit-v4">/);
  assert.match(loginCss, /\[hidden\]\s*\{\s*display:\s*none\s*!important;/);
  assert.match(html, /<script src="app\.js\?v=20260819-operations-audit-v4" defer><\/script>/);
  assert.match(html, /id="page-size"/);
  assert.match(html, /id="page-status"/);
  assert.match(script, /async function prepareLogin\(\)/);
  assert.match(script, /button\.href = url\.toString\(\)/);
  assert.match(script, /button\.setAttribute\('aria-disabled', 'false'\)/);
  assert.match(script, /if \(!state\.token\) \{ await prepareLogin\(\);/);
  assert.doesNotMatch(script, /login-button'\)\.addEventListener\('click'/);
  assert.match(script, /if \(params\.has\('error'\)\)/);
  assert.match(script, /refresh_interval_seconds/);
});

test('orders open on the pending dropshipper queue and expose Chatby intent', () => {
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  assert.match(script, /filters: \{ lifecycle: 'PENDING' \}/);
  assert.match(script, /view === 'orders' \? \{ lifecycle: 'PENDING' \} : \{\}/);
  assert.match(script, /Pendientes de Dropshipper/);
  assert.match(script, /latest_customer_intent/);
  for (const label of ['Todos', 'Con respuesta', 'Confirmar', 'Dirección', 'Incidencias', 'No confirmar', 'Revisión', 'Sin respuesta', 'No verificable']) assert.match(script, new RegExp(label));
  for (const field of ['Acción recomendada', 'Acción real', 'Respuesta del cliente', 'Cliente / importe']) assert.match(script, new RegExp(field));
  assert.match(script, /Pend\. Dropshipper/);
  assert.match(script, /Todos los estados/);
  assert.match(script, /Buscar ID Dropea/);
  assert.match(script, /customer_name/);
  assert.match(script, /external_order_reference/);
  assert.match(script, /orderReferenceLabel/);
  assert.match(script, /Confirmar según reglas/);
  assert.match(script, /mantener demoras y protecciones/);
  assert.match(script, /customer_response_status/);
  assert.match(script, /customer_response_summary/);
  assert.match(script, /customer_signal_association/);
  assert.match(script, /ID Dropea exacto del pedido/);
  assert.match(script, /Abrir únicamente los pedidos respondidos/);
  assert.match(script, /No aplica: no hay respuesta/);
  assert.match(script, /association exacta al pedido|asociación exacta al pedido/);
  assert.match(css, /signal-confirm/);
  assert.match(css, /summary-card\.filterable/);
});

test('incidents use current connector polls and distinguish a missing association from a connector error', () => {
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  assert.match(script, /customer_evidence/);
  assert.match(script, /operational_freshness_status/);
  assert.match(script, /Sin conversación asociada/);
  assert.match(script, /no se presupone que el cliente no respondió/i);
  assert.match(script, /No se ha ejecutado ninguna acción externa/i);
  assert.match(script, /Cliente \/ teléfono/);
  assert.match(script, /customer_phone/);
  assert.match(script, /latest_message/);
  assert.match(script, /Opción Dropea/);
  assert.match(script, /Mensajes del cliente en Chatby/);
});
