import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('Operations Center exposes exactly Pedidos and Incidencias with no write controls', () => {
  const html = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  const loginCss = fs.readFileSync(new URL('./login.css', import.meta.url), 'utf8');
  assert.equal((html.match(/class="nav-item/g) || []).length, 2);
  assert.match(html, />Pedidos</);
  assert.match(html, />Incidencias</);
  assert.doesNotMatch(`${html}\n${script}\n${css}`, /shopify/i);
  assert.equal((script.match(/method\s*:\s*['"]POST['"]/gi) || []).length, 1);
  assert.match(script, /openid-connect\/token/);
  assert.doesNotMatch(script, /method\s*:\s*['"](?:PUT|PATCH|DELETE)['"]/i);
  assert.match(html, /Acciones ejecutadas: 0/);
  assert.match(html, /MODO SIMULACIÓN/);
  assert.match(html, /NO SE HA ENVIADO NADA/);
  assert.match(html, /ACCIONES EJECUTADAS: 0/);
  assert.match(html, /<a id="login-button" class="primary-button" href="#" aria-disabled="true"/);
  assert.match(html, /id="login-notice"[^>]*role="alert"/);
  assert.match(html, /<link rel="stylesheet" href="login\.css\?v=20260808-hidden-fix-a00fe6d">/);
  assert.match(loginCss, /\[hidden\]\s*\{\s*display:\s*none\s*!important;/);
  assert.match(html, /<script src="app\.js\?v=20260808-login-native" defer><\/script>/);
  assert.match(script, /async function prepareLogin\(\)/);
  assert.match(script, /button\.href=url\.toString\(\)/);
  assert.match(script, /button\.setAttribute\('aria-disabled','false'\)/);
  assert.match(script, /if\(!state\.token\)\{await prepareLogin\(\);/);
  assert.doesNotMatch(script, /login-button'\)\.addEventListener\('click'/);
  assert.match(script, /if\(params\.has\('error'\)\)/);
  assert.match(script, /refresh_interval_seconds/);
});
