import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('Operations Center exposes Pedidos, Incidencias and the professional results dashboard without provider writes', () => {
  const html = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  const loginCss = fs.readFileSync(new URL('./login.css', import.meta.url), 'utf8');
  assert.equal((html.match(/class="nav-item/g) || []).length, 3);
  assert.match(html, />Pedidos</);
  assert.match(html, />Incidencias</);
  assert.match(html, />Panel de resultados</);
  assert.doesNotMatch(`${html}\n${script}\n${css}`, /shopify/i);
  assert.equal((script.match(/['"]POST['"]/gi) || []).length, 4);
  assert.match(script, /openid-connect\/token/);
  assert.doesNotMatch(script, /method\s*:\s*['"](?:PUT|DELETE)['"]/i);
  assert.match(script, /id \? 'PATCH' : 'POST'/);
  assert.match(html, /MODO OPERATIVO SEGURO/);
  assert.match(html, /CERO ACCIONES SOBRE PEDIDOS, CLIENTES O PROVEEDORES/);
  assert.match(html, /AJUSTES FINANCIEROS INTERNOS QUEDAN AUDITADOS/);
  assert.match(html, /id="finance-view"/);
  assert.match(html, /id="finance-month"/);
  assert.match(html, /RENDIMIENTO DEL NEGOCIO/);
  assert.match(script, /Beneficio conciliado/);
  assert.match(`${html}\n${script}`, /Beneficio neto/);
  assert.match(html, /Beneficio neto realizado por día/);
  assert.match(html, /Distribución del coste total del mes/);
  assert.match(html, /Detalle diario del mes/);
  assert.match(html, /id="finance-delivery-chart"/);
  assert.match(html, /id="finance-confirmation-chart"/);
  assert.match(html, /id="finance-history-chart"/);
  assert.match(html, /id="finance-prev-month"/);
  assert.match(html, /id="finance-next-month"/);
  assert.match(html, /id="finance-audit"/);
  assert.match(`${html}\n${script}`, /Coste de producto|Producto/);
  assert.match(script, /Dropea Public API V2/);
  assert.match(script, /totals\.exactNetProfit/);
  assert.doesNotMatch(script, /total_expenses\s*\|\|\s*0/);
  assert.match(script, /lifecycle_status/);
  assert.match(script, /simulated_decision/);
  assert.match(script, /customer_response_status/);
  assert.match(script, /normalized_type/);
  assert.match(script, /customer_evidence/);
  assert.match(script, /customer_signal_confidence/);
  assert.match(script, /incidents\/overview/);
  assert.match(script, /queueController\?\.abort/);
  assert.match(script, /detailController\?\.abort/);
  assert.match(script, /state\.offset >= data\.total/);
  assert.match(script, /tailored_recommendation/);
  assert.match(script, /prepared_dropea_solution/);
  assert.match(script, /READY_FOR_ADDRESS_AUTOMATION/);
  assert.match(script, /MANUAL_REVIEW_NO_RESPONSE/);
  assert.match(script, /LISTA PARA EL AGENTE AUTOMÁTICO/);
  assert.match(script, /Dirección aportada en Chatby/);
  assert.match(script, /source_truth/);
  assert.match(script, /Solución propuesta para esta incidencia/);
  assert.match(script, /Tu feedback se guarda como memoria operativa/);
  assert.match(script, /Estado de acción externa/);
  assert.doesNotMatch(script, /\b(?:canonical_state|proposed_resolution)\b/);
  assert.match(html, /<a id="login-button" class="primary-button" href="#" aria-disabled="true"/);
  assert.match(html, /id="login-notice"[^>]*role="alert"/);
  assert.match(html, /<link rel="stylesheet" href="login\.css\?v=20260808-hidden-fix-a00fe6d">/);
  assert.match(html, /<link rel="stylesheet" href="styles\.css\?v=20260913-finance-source-regression-v5">/);
  assert.match(loginCss, /\[hidden\]\s*\{\s*display:\s*none\s*!important;/);
  assert.match(html, /<script src="app\.js\?v=20260913-finance-source-regression-v5" defer><\/script>/);
  assert.match(html, /id="finance-fixed-form"/);
  assert.match(script, /saveFixedExpense/);
  assert.doesNotMatch(css, /finance-daily-table\{min-width:1900px/);
  assert.match(script, /className, 'results-daily-table'|results-daily-table/);
  assert.match(script, /Unidades devueltas/);
  assert.match(script, /Rechazados \/ devueltos/);
  assert.match(script, /dailyResultsChart/);
  assert.match(script, /chart-cumulative-line/);
  assert.match(script, /counts\.pendingConfirmation/);
  assert.match(script, /counts\.cancelledBeforeConfirmation/);
  assert.doesNotMatch(script, /\['Pendientes', counts\.pending, 'gray'\]/);
  assert.match(html, /id="finance-chart-profit"/);
  assert.match(html, /id="finance-chart-pnl"/);
  assert.match(html, /id="finance-history-window"/);
  assert.match(html, /id="finance-trend"/);
  assert.match(html, /class="finance-panel finance-audit-disclosure"/);
  assert.match(css, /results-chart-grid/);
  assert.match(css, /cost-breakdown-track/);
  assert.match(html, /id="finance-operational-summary"/);
  assert.match(html, /id="finance-data-summary"/);
  assert.match(html, /precisión interna constante[\s\S]*redondea una sola vez/);
  assert.match(script, /miniSparkline/);
  assert.match(script, /Datos conciliados/);
  assert.match(html, /Resultado anterior frente al resultado corregido/);
  assert.doesNotMatch(html, /Libro económico del mes/);
  assert.doesNotMatch(script, /orderLedgerTable/);
  assert.match(script, /reconciliationTable/);
  assert.doesNotMatch(html, /PRODUCTOS VENDIDOS/);
  assert.doesNotMatch(html, /id="finance-products"/);
  assert.match(html, /id="page-size"/);
  assert.match(html, /id="page-status"/);
  assert.match(script, /async function prepareLogin\(\)/);
  assert.match(script, /button\.href = url\.toString\(\)/);
  assert.match(script, /button\.setAttribute\('aria-disabled', 'false'\)/);
  assert.match(script, /if \(!state\.token\) \{ await prepareLogin\(\);/);
  assert.doesNotMatch(script, /login-button'\)\.addEventListener\('click'/);
  assert.match(script, /if \(params\.has\('error'\)\)/);
  assert.match(script, /refresh_interval_seconds/);
  assert.match(script, /finance_refresh_interval_seconds/);
  assert.match(script, /financeCache: new Map\(\)/);
  assert.match(script, /Se mantiene el último informe cargado/);
});

test('orders open on the pending dropshipper queue and expose Chatby intent', () => {
  const html = fs.readFileSync(new URL('./index.html', import.meta.url), 'utf8');
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  assert.match(script, /filters: \{\}/);
  assert.match(script, /coincide con la cola Pend\. Dropshipper/i);
  assert.match(script, /Solo pedidos pendientes en Dropea/);
  assert.match(script, /latest_customer_intent/);
  for (const label of ['Todos', 'Con respuesta', 'Confirmar', 'Dirección', 'Incidencias', 'No confirmar', 'Revisión', 'Sin respuesta', 'No verificable']) assert.match(script, new RegExp(label));
  for (const field of ['Acción recomendada', 'Acción real', 'Respuesta del cliente', 'Cliente / importe']) assert.match(script, new RegExp(field));
  assert.doesNotMatch(script, /Todos los estados/);
  assert.match(script, /Buscar ID Dropea/);
  assert.match(script, /customer_name/);
  assert.match(script, /external_order_reference/);
  assert.match(script, /orderReferenceLabel/);
  assert.match(script, /Confirmar según reglas/);
  assert.match(script, /mantener demoras y protecciones/);
  assert.match(script, /customer_response_status/);
  assert.match(script, /customer_response_summary/);
  assert.match(script, /customer_signal_association/);
  assert.match(script, /ID Dropea exacto del pedido/);
  assert.match(script, /Abrir únicamente los pedidos respondidos/);
  assert.match(script, /No aplica: no hay respuesta/);
  assert.match(script, /association exacta al pedido|asociación exacta al pedido/);
  assert.match(css, /signal-confirm/);
  assert.match(css, /summary-card\.filterable/);
  assert.match(script, /\['Devueltas', item\.returned_units\]/);
  assert.match(script, /Beneficio atribuible/);
  assert.match(script, /attributable_operational_profit/);
  assert.match(script, /Facturación real/);
  assert.match(script, /Gastos totales/);
  assert.match(script, /Publicidad Meta/);
  assert.match(`${html}\n${script}`, /Beneficio neto/);
  assert.match(script, /totals\.net_profit/);
});

test('incidents use current connector polls and distinguish a missing association from a connector error', () => {
  const script = fs.readFileSync(new URL('./app.js', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('./styles.css', import.meta.url), 'utf8');
  assert.match(script, /customer_evidence/);
  assert.match(script, /operational_freshness_status/);
  assert.match(script, /Sin conversación asociada/);
  assert.match(script, /no se presupone que el cliente no respondió/i);
  assert.match(script, /Estado de acción externa/i);
  assert.match(script, /Cliente \/ teléfono/);
  assert.match(script, /customer_phone/);
  assert.match(script, /latest_message/);
  assert.match(script, /Opción Dropea/);
  assert.match(script, /Conversación de la incidencia en Chatby/);
  assert.match(script, /Por qué propongo esta acción/);
  assert.match(script, /Cuándo no debe aplicarse/);
  assert.match(script, /item\.direction === 'OUTBOUND' \? 'Suleia' : 'Cliente'/);
  assert.match(script, /Aceptaron 5 €/);
  assert.match(script, /No aceptaron 5 €/);
  assert.match(script, /Esperando descuento/);
  assert.match(script, /discount_recovery/);
  assert.match(script, /Sólo se muestra “aceptado” o “no aceptado”/);
  assert.match(script, /Descuento 5 €/);
  assert.match(css, /discount-state\.accepted/);
  assert.match(css, /discount-state\.rejected/);
  assert.match(css, /discount-state\.waiting/);
});
