import test from 'node:test';
import assert from 'node:assert/strict';
import { absentDiscountReturnDecision } from './absent-discount-return.mjs';
import { executeIncidentDiscountNoResponseReturn } from './incidents.mjs';
const sent='2026-10-01T16:38:08.000Z', now=Date.parse(sent)+86400000;
const fixture=()=>({incident:{incidenceId:'2',orderId:'1',incidentType:'absent',phone:'34000000000',chatbyUserNs:'fixture',chatbyReadVerified:true,chatbyOrderAssociation:'EXACT_ORDER',absentDiscountOrderCreatedAt:'2026-09-20T00:00:00Z',absentDiscountIssue:{id:'2',order_id:'1',type:'RECIPIENT_ABSENT',status:'PENDING',is_active:true,delivery_attempt_number:2,created_at:'2026-09-29T00:00:00Z',allowed_resolution_options:['RETURN_REQUESTED']}},discountRecovery:{verified:true,templateName:'discount_fixture',sentAt:sent,responseStatus:'NO_RESPONSE'},messages:[{type:'agent',ts:Date.parse(sent)/1000,mid:'wamid.fixture',payload:{name:'discount_fixture'}}],now});
test('second absence returns at 24h after offer, never before',()=>{const f=fixture();assert.equal(absentDiscountReturnDecision({...f,now:now-1}).eligible,false);assert.equal(absentDiscountReturnDecision(f).eligible,true);});
test('requires exact live second absence, current-order offer and verified identity',()=>{for(const mutate of [f=>f.incident.absentDiscountIssue.delivery_attempt_number=1,f=>f.incident.absentDiscountIssue.is_active=false,f=>f.incident.absentDiscountIssue.order_id='old',f=>f.incident.absentDiscountIssue.status='RESOLVED',f=>f.incident.chatbyOrderAssociation='PHONE_FALLBACK',f=>f.discountRecovery.verified=false,f=>f.incident.absentDiscountOrderCreatedAt='2026-10-02T00:00:00Z',f=>f.incident.absentDiscountIssue.created_at='2026-10-02T00:00:00Z',f=>f.discountRecovery.sentAt='invalid',f=>f.discountRecovery.responseStatus='DISCOUNT_ACCEPTED',f=>f.discountRecovery.responseStatus='OTHER_RESPONSE',f=>f.discountRecovery.responseStatus='DISCOUNT_REJECTED',f=>delete f.messages[0].mid]){const f=fixture();mutate(f);assert.equal(absentDiscountReturnDecision(f).eligible,false);}});
test('any later or simultaneous inbound text/button/audio/unknown time blocks return',()=>{for(const m of [{type:'in',ts:now/1000,content:'Sí descuento'},{type:'in',ts:now/1000,msg_type:'postback'},{type:'in',content:'audio'},{type:'in',ts:Date.parse(sent)/1000}]){const f=fixture();f.messages.push(m);assert.equal(absentDiscountReturnDecision(f).eligible,false);}const f=fixture();f.messages.push({type:'in',ts:(Date.parse(sent)-1000)/1000});assert.equal(absentDiscountReturnDecision(f).eligible,true);});
function deps(f,changes={}){return {now,allowedIncidentIds:['2'],automaticEnabled:false,realEnabled:true,credentialAvailable:true,inspectPrior:async()=>({verified:false,blocked:false}),readCurrent:async()=>({issue:{raw:f.incident.absentDiscountIssue},order:{orderId:'1',status:'ERROR',customerPhone:f.incident.phone}}),readMessages:async()=>f.messages,claimReturn:async()=>({acquired:true,persistent:true,row:{attempted_at:new Date(now).toISOString()}}),finishReturn:async()=>{},auditReturn:async()=>{},verifyReturn:async()=>({verified:true}),...changes};}
test('executor posts exactly once, verifies and refuses persistent duplicate',async()=>{const f=fixture();let writes=0;const d=deps(f,{returnIssue:async()=>{writes++;return {};}});assert.equal((await executeIncidentDiscountNoResponseReturn(f.incident,f.discountRecovery,d)).verified,true);assert.equal(writes,1);d.claimReturn=async()=>({acquired:false,persistent:true,reason:'already_claimed',existing:{status:'verified'}});await executeIncidentDiscountNoResponseReturn(f.incident,f.discountRecovery,d);assert.equal(writes,1);});
test('late response during claim blocks write',async()=>{const f=fixture();let writes=0,finished;const d=deps(f,{claimReturn:async()=>{f.messages.push({type:'in',ts:now/1000,content:'Lo quiero'});return {acquired:true,persistent:true};},returnIssue:async()=>{writes++;},finishReturn:async r=>finished=r});const result=await executeIncidentDiscountNoResponseReturn(f.incident,f.discountRecovery,d);assert.equal(result.verified,false);assert.equal(writes,0);assert.equal(finished.status,'aborted');});
test('closed issue after claim blocks write',async()=>{const f=fixture();let writes=0;const d=deps(f,{claimReturn:async()=>{f.incident.absentDiscountIssue.status='RESOLVED';return {acquired:true,persistent:true};},returnIssue:async()=>{writes++;}});assert.equal((await executeIncidentDiscountNoResponseReturn(f.incident,f.discountRecovery,d)).verified,false);assert.equal(writes,0);});
